#!/bin/sh

# cutesie 'animation' while we wait
progBar()
{
    pid=$1
    delay=0.5
    barstr='*'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        printf "$barstr"
        sleep $delay
    done
}

sleep 30 &
progBar $! 
#printf "\n"


spin()
{
pid=$1
delay=0.05
spinstr='|/-\'
tput civis
while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
local temp=${spinstr#?}
printf " [%c]  " "$spinstr"
local spinstr=$temp${spinstr%"$temp"}
sleep $delay
printf "\b\b\b\b\b\b"
done
printf "   \b\b\b\b"
tput cnorm
}
sleep 5 &
spin $!
